// sidebars.js - sidebar entry point
module.exports = {
  learnSidebar: [
    {
      type: 'autogenerated',
      dirName: 'learn', 
    },
  ],
  buildSidebar: [
    {
      type: 'autogenerated',
      dirName: 'build', 
    },
  ],
  connectSidebar: [

    {
      type: 'autogenerated',
      dirName: 'connect', 
    },
  ],
  // consumeSidebar: [
  //   {
  //     type: 'autogenerated',
  //     dirName: 'consume', 
  //   },
  // ],

  deploySidebar: [
    {
      type: 'autogenerated',
      dirName: 'deploy', 
    },
  ],

  operateSidebar: [
    {
      type: 'autogenerated',
      dirName: 'operate', 
    },
  ],
  providersSidebar: [
    {
      type: 'autogenerated',
      dirName: 'providers', 
    },
  ],
  releaseNotesSidebar: [
    {
      type: 'category',
      label: 'Release Notes',
      items: [
        'rel-notes/up-cli/index',
        'rel-notes/mcp-connector/index',
        'rel-notes/spaces/index'
      ],
      collapsed: false
    }
  ],
    marketplaceSidebar: [
        {
            type: 'autogenerated',
            dirName: 'upbound-marketplace',
        },
    ],
  solutionsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'solutions',
    }
  ],
};
