# .github/ISSUE_TEMPLATE/content.yml  

name: Content Request
description: Request new documentation or guides
title: "[CONTENT]: "
labels: ["content-request"]
body:
  - type: markdown
    attributes:
      value: |
        **For major content additions**, consider creating a Linear issue first to discuss scope and approach.

  - type: input
    id: feature_area
    attributes:
      label: Feature or topic area
      placeholder: "e.g., UXP , Providers, Spaces, CLI"
    validations:
      required: true

  - type: dropdown
    id: content_type
    attributes:
      label: What type of content?
      options:
        - Tutorial/How-to guide
        - Conceptual explanation
        - API reference
        - Example/code sample
        - Migration guide
        - Troubleshooting guide
        - Other
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: Use case or problem
      description: What are you trying to accomplish? What problem does this solve?
      placeholder: "Describe the use case or problem this documentation would address..."
    validations:
      required: true

  - type: dropdown
    id: audience
    attributes:
      label: Target audience
      options:
        - New users/getting started
        - Experienced users
        - Developers/technical
        - Platform administrators
        - Mixed audience
