# .github/ISSUE_TEMPLATE/docs-issue.yml
name: Documentation Issue
description: Report a docs problem or suggest improvements
title: "[DOCS]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation! 
        
        **Quick fixes welcome**: For typos or small corrections, feel free to submit a PR directly.

  - type: dropdown
    id: issue_type
    attributes:
      label: What type of issue is this?
      options:
        - Content is incorrect or unclear
        - Missing documentation
        - Broken link
        - Typo or formatting issue
        - Other
    validations:
      required: true

  - type: input
    id: page_url
    attributes:
      label: Page URL (if applicable)
      placeholder: "https://docs.upbound.io/path/to/page"

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What's the issue? What would you like to see?
      placeholder: "Describe the problem or improvement..."
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context, screenshots, or examples
      placeholder: "Any additional details that might help..."
