module.exports = {
    getstartedSidebar: [
        {
            type: "autogenerated",
            dirName: "getstarted",
        },
    ],
    guidesSidebar: [
        {
            type: "autogenerated",
            dirName: "guides",
        },
    ],
    manualsSidebar: [
        "manuals/index",
        {
            type: "category",
            label: "Upbound Crossplane",
            link: {
                type: "doc",
                id: "manuals/uxp/overview",
            },
            items: [
                {
                    type: "autogenerated",
                    dirName: "manuals/uxp",
                },
            ],
        },
        {
            type: "link",
            label: "Spaces",
            href: "/spaces/latest/overview",
        },
        {
            type: "category",
            label: "CLI",
            link: {
                type: "doc",
                id: "manuals/cli/overview",
            },
            items: [
                {
                    type: "autogenerated",
                    dirName: "manuals/cli",
                },
            ],
        },
        {
            type: "category",
            label: "Console",
            items: [
                {
                    type: "autogenerated",
                    dirName: "manuals/console",
                },
            ],
        },
        {
            type: "category",
            label: "Official Packages",
            link: {
                type: "doc",
                id: "manuals/packages/overview",
            },
            items: [
                {
                    type: "autogenerated",
                    dirName: "manuals/packages",
                },
            ],
        },
        {
            type: "category",
            label: "Marketplace",
            link: {
                type: "doc",
                id: "manuals/marketplace/overview",
            },
            items: [
                {
                    type: "autogenerated",
                    dirName: "manuals/marketplace",
                },
            ],
        },
        {
            type: "category",
            label: "Platform",
            link: {
                type: "doc",
                id: "manuals/platform/overview",
            },
            items: [
                {
                    type: "autogenerated",
                    dirName: "manuals/platform",
                },
            ],
        },
    ],
    referenceSidebar: [
        {
            type: "autogenerated",
            dirName: "reference",
        },
    ],
};
