module.exports = {
    getstartedSidebar: [
        {
            type: "autogenerated",
            dirName: "getstarted",
        },
    ],
    guidesSidebar: [
        {
            type: "autogenerated",
            dirName: "guides",
        },
    ],
    manualsSidebar: [
        {
            type: "autogenerated",
            dirName: "manuals",
        },
    ],
    referenceSidebar: [
        {
            type: "autogenerated",
            dirName: "reference",
        },
    ],
};
