module.exports = {
  fundamentalsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'fundamentals',
    },
  ],

  uxpSidebar: [
    {
      type: 'autogenerated',
      dirName: 'uxp',
    },
  ],

  upboundSidebar: [
    {
      type: 'autogenerated',
      dirName: 'spaces',
    },
  ],

  referenceSidebar: [
    {
      type: 'autogenerated',
      dirName: 'reference',
    },
  ],

  solutionsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'solutions',
    },
  ],
};
