apiVersion: spaces.upbound.io/v1beta1
kind: ControlPlane
metadata:
  name: controlplanes.spaces.upbound.io
  namespace: default
spec:
  group: spaces.upbound.io
  names:
    kind: ControlPlane
    listKind: ControlPlaneList
    plural: controlplanes
    singular: controlplane
  scope: Namespaced
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        description: ControlPlane configures details about the Crossplane instance
          running in the managed control plane environment.
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              crossplane:
                properties:
                  autoUpgrade:
                    properties:
                      channel:
                        description: 'Optional: The upgrade channel determines the
                          cadence by which a control plane upgrades to the next version.
                          Can be either None, Patch, Stable, or Rapid. By default,
                          it is Stable.'
                        type: string
                    type: object
                  version:
                    description: 'Optional: Specify the desired UXP (Crossplane) version
                      for this control plane to run. If not specified, it is inferred
                      from the autoUpgrade.channel.'
                    type: string
                type: object
              source:
                description: THIS IS AN ALPHA FIELD. Do not use it in production.
                  Source points to a Git repository containing a ControlPlaneSource
                  manifest with the desired state of the ControlPlane's configuration.
                properties:
                  git:
                    properties:
                      auth:
                        properties:
                          type:
                            description: Other options are Basic, BearerToken, and
                              SSH. Default is no authentication.
                            type: string
                        type: object
                      path:
                        description: Path within the Git repository to pull the Control
                          Plane Source from. Default is the root of the repository.
                        type: string
                      pullInterval:
                        description: Interval at which the Git repository should be
                          polled for changes. Default is 90s. Minimum is 15s.
                        type: string
                      ref:
                        properties:
                          branch:
                            description: Other options are commit and tag. Default
                              is the main branch.
                            type: string
                        type: object
                      url:
                        description: This is the URL of the Git repository to pull
                          the Control Plane source.
                        type: string
                    type: object
                type: object
              writeConnectionSecretToRef:
                description: Specifies the namespace and name of a Secret to which
                  any connection details (i.e., kubeconfig) for the control plane
                  should be written.
                properties:
                  name:
                    type: string
                  namespace:
                    type: string
                required:
                - name
                - namespace
                type: object
            required:
            - crossplane
            type: object
        type: object
    served: true
    storage: true
