apiVersion: spaces.upbound.io/v1beta1
kind: SharedSecretStores
metadata:
  name: sharedsecretstores.spaces.upbound.io
  namespace: default
spec:
  group: spaces.upbound.io
  names:
    kind: SharedSecretStore
    listKind: SharedSecretStoreList
    plural: sharedsecretstores
    singular: sharedsecretstore
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: SharedSecretStore configures how SecretStores are shared across
          control planes.
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              controlPlaneSelector:
                description: The store is projected only to control planes matching
                  the provided label selector.
                properties:
                  labelSelectors:
                    items:
                      type: string
                    type: array
                  names:
                    items:
                      type: string
                    type: array
                type: object
              namespaceSelector:
                description: Project SecretStores instances into namespaces matching
                  the declared criteria.
                properties:
                  matchLabels:
                    additionalProperties:
                      type: string
                    type: object
                  names:
                    items:
                      type: string
                    type: array
                type: object
              provider:
                properties:
                  vault:
                    properties:
                      auth:
                        properties:
                          appRole:
                            description: AppRole auth for Vault.
                            properties:
                              path:
                                type: string
                              roleId:
                                type: string
                              secretRef:
                                properties:
                                  key:
                                    type: string
                                  name:
                                    type: string
                                type: object
                            type: object
                          kubernetes:
                            description: Kubernetes auth for Vault.
                            properties:
                              mountPath:
                                type: string
                              role:
                                type: string
                              secretRef:
                                properties:
                                  key:
                                    type: string
                                  name:
                                    type: string
                                type: object
                              serviceAccountRef:
                                properties:
                                  name:
                                    type: string
                                type: object
                            type: object
                          tokenSecretRef:
                            description: Static token for Vault authentication.
                            properties:
                              key:
                                type: string
                              name:
                                type: string
                            type: object
                        type: object
                      caBundle:
                        description: Base64 encoded string of certificate.
                        type: string
                      caProvider:
                        description: Instead of caBundle you can also specify a caProvider
                          to retrieve the cert from a Secret or ConfigMap.
                        properties:
                          key:
                            type: string
                          name:
                            type: string
                          type:
                            type: string
                        type: object
                      namespace:
                        description: Vault enterprise namespace.
                        type: string
                      path:
                        description: Path is the mount path of the Vault KV backend
                          endpoint. Used as a path prefix for the external secret
                          key.
                        type: string
                      server:
                        type: string
                      version:
                        description: Version is the Vault KV secret engine version.
                          This can be either "v1" or "v2", defaults to "v2".
                        type: string
                    type: object
                required:
                - provider
                type: object
              retrySettings:
                description: Specify retry settings for the HTTP connection.
                properties:
                  maxRetries:
                    type: integer
                  retryInterval:
                    type: string
                type: object
              secretStoreMetadata:
                description: The metadata of the secret store to be created.
                properties:
                  labels:
                    additionalProperties:
                      type: string
                    type: object
                type: object
              secretStoreName:
                description: Optional, the name to be used on external-secrets.io/v1beta1
                  SecretStores created in the control plane. If not set, SharedSecretStore
                  name will be used.
                type: string
            required:
            - secretStoreMetadata
            - controlPlaneSelector
            - namespaceSelector
            - provider
            type: object
        type: object
    served: true
    storage: true
