apiVersion: spaces.upbound.io/v1alpha1
kind: SharedExternalSecret
metadata:
  name: shared-vault-secret
  namespace: default
spec:
  externalSecretName: my-secret
  externalSecretMetadata:
    labels:
      acmeco/label: my-label
  controlPlaneSelector:
    labelSelectors:
      - controlplane: dev
    names:
      - ctp1
      - ctp2
  namespaceSelector:
    matchLabels:
      - controlplane: dev
    names:
      - ns1
      - ns2
  refreshTime: 1m
  externalSecretSpec: null
  secretStoreRef:
    name: secret-store-name
    kind: SecretStore
    refreshInterval: 1h
  target:
    name: my-secret
    creationPolicy: Merge
    template:
      type: kubernetes.io/dockerconfigjson
      metadata:
        annotations: {}
        labels: {}
      data:
        config.yml: |
          endpoints:
          - https://{{ .data.user }}:{{ .data.password }}@api.exmaple.com
      templateFrom:
        - configMap:
            name: alertmanager
            items:
              - key: alertmanager.yaml
  data:
    - secretKey: secret-key-to-be-managed
      remoteRef:
        key: provider-key
        version: provider-key-version
        property: provider-key-property
  dataFrom:
    - key: provider-key
      version: provider-key-version
      property: provider-key-property
