DirectoryPath: "build"
CheckExternal: true
IgnoreInternalEmptyHash: true
HTTPTimeout: 15
HTTPConcurrentRequests: 4
IgnoreURLs:
  - "/crds/(.*).yaml"  # CRD YAML static assets
  - "localhost"
  - "127.0.0.1"
