/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Upbound Documentation",
  "tagline": "Guide your internal cloud platform journey",
  "favicon": "img/icons/favicon.ico",
  "url": "https://docs.upbound.io",
  "baseUrl": "/",
  "organizationName": "upbound",
  "projectName": "docs",
  "onBrokenLinks": "warn",
  "onBrokenMarkdownLinks": "warn",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": false,
        "blog": false,
        "theme": {
          "customCss": "./src/css/custom.css"
        }
      }
    ]
  ],
  "plugins": [
    [
      "docusaurus-pushfeedback",
      {
        "project": "0p5hvygqxb"
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "learn",
        "path": "docs/learn",
        "routeBasePath": "/",
        "sidebarPath": "/Users/rae/docs/src/sidebars/learn.js"
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "build",
        "path": "docs/build",
        "routeBasePath": "build",
        "sidebarPath": "/Users/rae/docs/src/sidebars/build.js"
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "deploy",
        "path": "docs/deploy",
        "routeBasePath": "deploy",
        "sidebarPath": "/Users/rae/docs/src/sidebars/deploy.js"
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "operate",
        "path": "docs/operate",
        "routeBasePath": "operate",
        "sidebarPath": "/Users/rae/docs/src/sidebars/operate.js"
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "connect",
        "path": "docs/connect",
        "routeBasePath": "connect",
        "sidebarPath": "/Users/rae/docs/src/sidebars/connect.js"
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "providers",
        "path": "docs/providers",
        "routeBasePath": "providers",
        "sidebarPath": "/Users/rae/docs/src/sidebars/providers.js"
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "apis-cli",
        "path": "docs/apis-cli",
        "routeBasePath": "apis-cli",
        "sidebarPath": "/Users/rae/docs/src/sidebars/apis-cli.js"
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "release-notes",
        "path": "docs/release-notes",
        "routeBasePath": "release-notes",
        "sidebarPath": "/Users/rae/docs/src/sidebars/release-notes.js"
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "marketplace",
        "path": "docs/upbound-marketplace",
        "routeBasePath": "upbound-marketplace",
        "sidebarPath": "/Users/rae/docs/src/sidebars/marketplace.js"
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "usage",
        "path": "docs/usage",
        "routeBasePath": "usage",
        "sidebarPath": "/Users/rae/docs/src/sidebars/usage.js"
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "crossplane-learn",
        "path": "docs/crossplane/learn",
        "routeBasePath": "crossplane/learn",
        "sidebarPath": "/Users/rae/docs/src/sidebars/crossplane-learn.js"
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "crossplane-api-ref",
        "path": "docs/crossplane/api-ref",
        "routeBasePath": "crossplane/api-ref",
        "sidebarPath": "/Users/rae/docs/src/sidebars/crossplane-api-ref.js"
      }
    ]
  ],
  "themeConfig": {
    "navbar": {
      "title": "",
      "logo": {
        "alt": "Upbound Logo",
        "src": "img/logos/upbound-docs.svg",
        "srcDark": "img/logos/up-docs-white.svg"
      },
      "items": [
        {
          "type": "docSidebar",
          "sidebarId": "learnSidebar",
          "position": "left",
          "label": "Learn",
          "docsPluginId": "learn"
        },
        {
          "type": "docSidebar",
          "sidebarId": "buildSidebar",
          "position": "left",
          "label": "Build",
          "docsPluginId": "build"
        },
        {
          "type": "docSidebar",
          "sidebarId": "deploySidebar",
          "position": "left",
          "label": "Deploy",
          "docsPluginId": "deploy"
        },
        {
          "type": "docSidebar",
          "sidebarId": "operateSidebar",
          "position": "left",
          "label": "Operate",
          "docsPluginId": "operate"
        },
        {
          "type": "docSidebar",
          "sidebarId": "connectSidebar",
          "position": "left",
          "label": "Connect",
          "docsPluginId": "connect"
        },
        {
          "type": "dropdown",
          "label": "Reference",
          "position": "left",
          "items": [
            {
              "type": "docSidebar",
              "sidebarId": "apisCliSidebar",
              "label": "APIs & CLIs",
              "docsPluginId": "apis-cli"
            },
            {
              "type": "docSidebar",
              "sidebarId": "marketplaceSidebar",
              "label": "Upbound Marketplace",
              "docsPluginId": "marketplace"
            },
            {
              "type": "docSidebar",
              "sidebarId": "releaseNotesSidebar",
              "label": "Release Notes",
              "docsPluginId": "release-notes"
            },
            {
              "type": "docSidebar",
              "sidebarId": "providersSidebar",
              "label": "Providers",
              "docsPluginId": "providers"
            },
            {
              "type": "docSidebar",
              "sidebarId": "usageSidebar",
              "label": "Usage",
              "docsPluginId": "usage"
            }
          ]
        },
        {
          "type": "search",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "algolia": {
      "appId": "4OZX85VEXQ",
      "apiKey": "7880f8f03cb89ce23f18d4359fb10e5e",
      "indexName": "upbound-docs",
      "contextualSearch": true,
      "searchPagePath": "search",
      "searchParameters": {}
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Use Upbound",
          "items": [
            {
              "label": "Get Started",
              "to": "/"
            }
          ]
        },
        {
          "title": "Build With Upbound",
          "items": [
            {
              "label": "Control Planes",
              "to": "/build"
            }
          ]
        },
        {
          "title": "Community",
          "items": [
            {
              "label": "Slack",
              "href": "https://slack.crossplane.io"
            },
            {
              "label": "GitHub",
              "href": "https://github.com/upbound"
            },
            {
              "label": "Twitter",
              "href": "https://twitter.com/upbound_io"
            }
          ]
        },
        {
          "title": "More",
          "items": [
            {
              "label": "Blog",
              "href": "https://blog.upbound.io"
            },
            {
              "label": "Support",
              "href": "https://upbound.zendesk.com/"
            },
            {
              "label": "Crossplane Docs",
              "href": "https://docs.crossplane.io"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2025 Upbound. All rights reserved."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [
        "bash",
        "yaml",
        "json",
        "go",
        "python"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": true
    },
    "docs": {
      "sidebar": {
        "hideable": true,
        "autoCollapseCategories": true
      },
      "versionPersistence": "localStorage"
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "future": {
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    }
  }
};
